[package]
name = "td-rs-sop"
version = "0.1.0"
edition = "2021"

[lib]
name = "td_rs_sop"
crate-type = ["lib", "staticlib"]

[dependencies]
libc = "*"
cxx = "1"
td-rs-base = { path = "../td-rs-base" }

[build-dependencies]
cxx-build = "1"