[package]
name = "td-rs-autocxx-build"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx-build = { git = "https://github.com/tychedelia/autocxx.git", branch = "main" }
miette = { version="5", features = [ "fancy" ] }
