[package]
name = "td-rs-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
cxx = "1"
rgb = "0.8.36"

[build-dependencies]
cxx-build = "1"