[package]
name = "td-rs-base"
version = "0.1.0"
edition = "2021"

[lib]
name = "td_rs_base"
crate-type = ["lib", "staticlib"]

[dependencies]
autocxx = "0.25.0"
cxx = "1.0.78"
rgb = "0.8.36"

[build-dependencies]
autocxx-build = "0.25.0"
miette = { version="5", features = [ "fancy" ] }